### ISSUE TITLE
Component Localization 

### ISSUE THREAD

**Issue by MarioTainaka** [MarioTainaka/SH2HDCVP-Offline-Installer#2]
While components do show and work as intended the descriptions are only available  in English because I don't know how to do multi language custom descriptions for components.  Any help would be appreciated.

**Comment by MarioTainaka** [comment]
Yeah know i'm stuck on this. @nipkownix your help would be greatly appreciated on

**Comment by MarioTainaka** [comment]
Yeah, i'm stuck on this @nipkownix  your help would be greatly appreciated.

**Comment by MarioTainaka** [comment]
Yeah, i'm stuck on this @nipkownix  your help would be greatly appreciated.

**Comment by MarioTainaka** [comment]
@nipkownix  I hope you're well! I really need your help with this. Thanks again!

**Comment by nipkownix** [comment]
Oh hi! I hadn't noticed this issue.
I'll see if I can take a look at it soon.

**Comment by MarioTainaka** [comment]
> Oh hi! I hadn't noticed this issue. I'll see if I can take a look at it soon.

bless you!!
