### ISSUE TITLE
Component Names Localization 

### ISSUE THREAD

**Issue by MarioTainaka** [MarioTainaka/SH2HDCVP-Offline-Installer#4]
@nipkownix  this one's on me I actually worded the initial post wrong. Sorry about that. But could you also add component localization for the different languages as well? thanks a bunch

**Comment by nipkownix** [comment]
Hmm, what do you mean exactly? I'm not sure I understand 🫠

**Comment by MarioTainaka** [comment]
> Hmm, what do you mean exactly? I'm not sure I understand 🫠

@nipkownix  All this right here :) Sorry if I wasn't clear on that.

![image](https://github.com/MarioTainaka/SH2HDCVP-Offline-Installer/assets/32436919/745caf77-6cd1-4493-8a5c-40f497cfbc11)

**Comment by nipkownix** [comment]
Ahh, you mean their actual titles, right. Will take a look at it later tonight. Sorry!

**Comment by MarioTainaka** [comment]
> Ahh, you mean their actual titles, right. Will take a look at it later tonight. Sorry!

Thank you!!

**Comment by nipkownix** [comment]
Let me know if #5 is enough.

**Comment by MarioTainaka** [comment]
> Let me know if #5 is enough.

Yup this is perfect!! thank you.
